export const ADD_TIME_ENTRY = 'ADD_TIME_ENTRY'
export const ADD_CURRENT_TIME = 'ADD_CURRENT_TIME'
export const ADD_CURRENT_TEXT = 'ADD_CURRENT_TEXT'
export const TOGGLE_TIMER_STATUS = 'TOGGLE_TIMER_STATUS'